[tool.poetry]
name = "DragonPyEmulator"
version = "0.7.0"
description = "Emulator for 6809 CPU based system like Dragon 32 / CoCo written in Python..."
authors = ["JensDiemer <git@jensdiemer.de>"]
packages = [{ include = "dragonpy" }]
keywords=["Emulator","6809","Dragon","CoCo","Vectrex","tkinter","pypy"]
classifiers = [
    # http://pypi.python.org/pypi?%3Aaction=list_classifiers
    "Development Status :: 5 - Production/Stable",
    "Environment :: MacOS X",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications",
    "Environment :: Other Environment",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: System :: Emulators",
    "Topic :: Software Development :: Assemblers",
    "Topic :: Software Development :: Testing",
]

# Will be generated from README.creole with: "poetry run update_rst_readme"
readme="README.rst"


[tool.poetry.dependencies]
python = ">=3.7,<4.0"
dragonlib = "*"
MC6809 = "*"
click = "^7.0"
pygments = "^2.5.2"

[tool.poetry.dev-dependencies]
dev_shell = "*"  # https://github.com/jedie/dev-shell
python-creole = "*"
poetry_publish = "*"
tox = "*"
pytest = "*"
pytest-cov = "*"
pytest-darker = "*"  # https://github.com/akaihola/pytest-darker
pytest-flake8 = "*"
pytest-isort = "*"
darker = "*"  # https://github.com/akaihola/darker
black = "==21.12b0" # https://github.com/akaihola/darker/issues/264

[tool.poetry.scripts]
devshell = 'dragonpy.dev_shell:devshell_cmdloop'
DragonPy = "dragonpy.core.cli:main"
update_rst_readme = "dragonpy.publish:update_readme"
publish = "dragonpy.publish:publish"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[tool.darker]
src = ['.']
revision = "origin/main..."
line_length = 120
verbose = true
skip_string_normalization = true
diff = false
check = false
stdout = false
isort = true
lint = [
    "flake8",
]
log_level = "INFO"


[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/config_files/#pyprojecttoml-preferred-format
atomic=true
profile='black'
line_length=120
skip_glob=[".*", "*/htmlcov/*",]
known_first_party=["dragonpy", "PyDC"]
lines_after_imports=2


[tool.coverage.run]
omit = [".*"]


[tool.pytest.ini_options]
# https://docs.pytest.org/en/latest/customize.html#pyproject-toml
minversion = "6.0"
norecursedirs = ".* .venv .git __pycache__ coverage* dist htmlcov"
# sometimes helpfull "addopts" arguments:
#    -vv
#    --verbose
#    --capture=no
#    --trace-config
#    --full-trace
#    -p no:warnings
addopts = """
    --import-mode=importlib
    --cov=.
    --cov-report term-missing
    --cov-report html
    --cov-report xml
    --no-cov-on-fail
    --showlocals
    --darker
    --flake8
    --isort
    --doctest-modules
    --failed-first
    --last-failed-no-failures all
    --new-first
    -p no:randomly
"""
# TODO: --mypy


[tool.tox]
# https://tox.readthedocs.io/en/latest/example/basic.html#pyproject-toml-tox-legacy-ini
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py39,py38,py37
skip_missing_interpreters = True
[testenv]
passenv = *
whitelist_externals = pytest
commands =
    pytest --workers auto --tests-per-worker 1
"""
